language: ruby

bundler_args: '--binstubs --without documentation'
before_install: gem install bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5

addons:
  code_climate:
    repo_token: 03009a663136471abb5d7aa1ee312511e22021da48358ee8700b6aa34ffd3622