language: ruby
cache: bundler
sudo: false
rvm:
- 2.3.1
- 2.2
- 2.1
- 2.0
notifications:
  hipchat:
    rooms:
      secure: g6Ve1qDiVR9VHOJwXVr4iXEMZNfLUL2iBlGzF9XVNySJxYmPOpfOhb+GjN2vefTvloZVgRvTeXE/9rldk6OPseXqMCuLP8wbXm3TeKQDhsjeyWQt4oXUKk5PePZK83PJiv7VnW09eRIwPkUhFWOeCV8qZxREHseyxz8VZllfUN4=
  template:
        - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
  notify: true